wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1740836033.712194
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 54
      - 55
      - 77
      3:
      - 1
      - 5
      - 14
      - 16
      - 23
      4: 3.8.13
      5: 0.13.4
      8:
      - 5
dropout:
  desc: null
  value: 0.6
feat_mat:
  desc: null
  value: 1024
gradclip:
  desc: null
  value: 1.0
hidden:
  desc: null
  value: 64
lambda:
  desc: null
  value: 0.1
loss_type:
  desc: null
  value: BCE
lr:
  desc: null
  value: 0.01
lr_cent:
  desc: null
  value: 0.1
n_heads:
  desc: null
  value: 8
output:
  desc: null
  value: 16
pc_att_channels:
  desc: null
  value: 16
plot:
  desc: null
  value: false
theta:
  desc: null
  value: 0.3
wd:
  desc: null
  value: 1.0e-05
